### ISSUE TITLE
First Time Setup problems

### ISSUE THREAD

**Issue by macjeff** [brianmtreese/nodejs-pool-controller-polyglotv2#4]
I am setting up for the first time.  I can get it to show up in the ISY but I cant get it to talk to my actual circuits.  

I believe the issue is the URL.   I have Screenlogic 2 and I put in my internal IP of the screenlogic interface and it wont work.  What am I doing wrong?

**Comment by brianmtreese** [comment]
The URL will need to be the URL of your nodejs pool controller app. The node server uses this URL to access the API to communicate with your pool circuits.

**Comment by brianmtreese** [comment]
Hey @macjeff , just wanted to check in with you, did this solve your problem?

**Comment by macjeff** [comment]
Yes.  But I missed that you need a special board for this to work and it looks like the one that most people use is no longer made.  Any ideas?
